import Head from "next/head";
import { useState } from "react";
import Query from "../components/Query";
import Notification from "../components/Notification";
import Register from "../components/Register";

export default function Home() {
  const [mode, setMode] = useState("Query");

  const toggleMode = (event) => {
    const modes = ["Query", "Register", "Notification"];
    const idx = modes.indexOf(mode);
    setMode(modes[idx + 1 < modes.length ? idx + 1 : 0]);
  };

  const getUIMode = () => {
    switch (mode) {
      case "Register":
        return <Register />;
      case "Notification":
        return <Notification />;
      case "Query":
      default:
        return <Query />;
    }
  };

  return (
    <div
      className="d-flex justify-content-center align-items-center"
      style={{ height: "100vh" }}
    >
      <Head>
        <title>TS System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <center style={{ width: "500px" }}>
        <h1 className="mb-0">Tutor-Student</h1>
        <h4>System</h4>

        <button
          type="button"
          className="btn btn-sm btn-outline-primary mt-3 mb-2"
          style={{ width: "150px" }}
          onClick={toggleMode}
        >
          Mode: {mode}
        </button>
        <div style={{ minHeight: "250px" }}>{getUIMode()}</div>
      </center>
    </div>
  );
}
